services:
  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    environment:
      - INFLUXDB_DB=stationmeteo
      - INFLUXDB_USER=user
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=s3cr3t 
networks:
  monitoring:
volumes:
  influxdb-storage:
